AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  image-resize

  Sample SAM Template for image-resize

Parameters:
  Subnet1:
    Type: AWS::EC2::Subnet::Id
  Subnet2:
    Type: AWS::EC2::Subnet::Id
  VpcId:
    Type: AWS::EC2::VPC::Id
  BucketName:
    Type: String

Globals:
  Function:
    Timeout: 10
    MemorySize: 1024

Resources:
  ImageResizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image-resize/
      Handler: image-resize
      Runtime: go1.x
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: ImageResizeFunctionPermission
    Properties:
      TargetType: lambda
      Targets:
        - Id: !GetAtt ImageResizeFunction.Arn

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ImageResizeFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ImageResizeFunction
      Principal: elasticloadbalancing.amazonaws.com

  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName

Outputs:
  LoadBalancerDNSName:
    Description: "ALB endpoint URL for Image Resize Function"
    Value: !GetAtt LoadBalancer.DNSName
  ImageResizeFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ImageResizeFunction.Arn
  ImageResizeFunctionIamRole:
    Description: "Implicit IAM Role created for Image Resize function"
    Value: !GetAtt ImageResizeFunctionRole.Arn
